package com.urban.intelligence.platform.domain.repository;

import com.urban.intelligence.platform.domain.entity.Recommendation;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

/**
 * RecommendationRepository - Data access layer for Recommendation entities.
 *
 * PHASE 3: Added dedup support via content_hash and existence check query.
 *          Added batch operations for saveAll() usage.
 */
@Repository
public interface RecommendationRepository extends JpaRepository<Recommendation, Long> {

    Page<Recommendation> findByDistrict_Id(Long districtId, Pageable pageable);

    Page<Recommendation> findByPriority(Recommendation.Priority priority, Pageable pageable);

    Page<Recommendation> findByAutoGeneratedTrue(Pageable pageable);

    List<Recommendation> findByCreatedAtAfter(LocalDateTime timestamp);

    @Query("SELECT r FROM Recommendation r WHERE r.district.id = :districtId " +
           "AND r.priority IN ('HIGH', 'CRITICAL') " +
           "ORDER BY r.priority DESC, r.createdAt DESC")
    List<Recommendation> findUrgentRecommendationsByDistrict(@Param("districtId") Long districtId);

    @Query("SELECT r.priority, COUNT(r) FROM Recommendation r " +
           "WHERE r.createdAt >= :startDate GROUP BY r.priority")
    List<Object[]> getRecommendationPriorityDistribution(@Param("startDate") LocalDateTime startDate);

    Long countByPriority(Recommendation.Priority priority);

    Long countByDistrict_Id(Long districtId);

    /**
     * Check for duplicate auto-generated recommendation.
     * Uses content_hash for fast dedup lookup (Phase 3).
     */
    Optional<Recommendation> findByContentHashAndAutoGeneratedTrue(String contentHash);

    /**
     * Find existing recommendation matching type, district, and message.
     * Used as dedup fallback for content_hash misses.
     */
    @Query("SELECT r FROM Recommendation r WHERE r.type = :type " +
           "AND r.district.id = :districtId AND r.message = :message " +
           "AND r.autoGenerated = true")
    Optional<Recommendation> findDuplicateGenerated(
        @Param("type") String type,
        @Param("districtId") Long districtId,
        @Param("message") String message);

    /**
     * Delete auto-generated recommendations older than the cutoff date.
     * Used by scheduled cleanup job (Phase 6).
     */
    @Modifying
    @Query("DELETE FROM Recommendation r WHERE r.autoGenerated = true AND r.createdAt < :cutoff")
    int deleteOldAutoGenerated(@Param("cutoff") LocalDateTime cutoff);

    long countByAutoGeneratedTrue();
}
