package com.urban.intelligence.platform.domain.entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "recommendations", indexes = {
    @Index(name = "idx_recommendation_district", columnList = "district_id"),
    @Index(name = "idx_recommendation_priority", columnList = "priority"),
    @Index(name = "idx_recommendation_created_at", columnList = "created_at"),
    @Index(name = "idx_recommendation_content_hash", columnList = "content_hash"),
    @Index(name = "idx_recommendation_confidence", columnList = "operational_confidence")
})
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Recommendation {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, length = 100)
    private String type;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Priority priority;

    @Column(nullable = false, columnDefinition = "TEXT")
    private String message;

    @Builder.Default
    @Column(name = "auto_generated", nullable = false)
    private Boolean autoGenerated = false;

    @Column(name = "content_hash", length = 64)
    private String contentHash;

    @Column(name = "predicted_impact")
    private Double predictedImpact;

    @Column(name = "intervention_effectiveness")
    private Double interventionEffectiveness;

    @Column(name = "operational_confidence")
    private Double operationalConfidence;

    @Builder.Default
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private RecommendationStatus status = RecommendationStatus.PENDING;

    @Column(length = 120)
    private String reviewedBy;

    private LocalDateTime reviewedAt;

    @Column(columnDefinition = "TEXT")
    private String reviewNotes;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "district_id", nullable = false)
    private District district;

    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(nullable = false)
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }

    public enum Priority {
        LOW, MEDIUM, HIGH, CRITICAL
    }

    public enum RecommendationStatus {
        PENDING, APPROVED, REJECTED, IMPLEMENTED
    }
}
