package com.urban.intelligence.platform.analytics;

import com.urban.intelligence.platform.domain.entity.AnalyticsEvent;
import com.urban.intelligence.platform.domain.entity.District;
import com.urban.intelligence.platform.domain.entity.Incident;
import com.urban.intelligence.platform.domain.entity.Recommendation;
import com.urban.intelligence.platform.domain.repository.AnalyticsEventRepository;
import com.urban.intelligence.platform.domain.repository.DistrictRepository;
import com.urban.intelligence.platform.domain.repository.IncidentRepository;
import com.urban.intelligence.platform.domain.repository.RecommendationRepository;
import com.urban.intelligence.platform.dto.analytics.OperationalInsightResponse;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.*;
import java.util.stream.Collectors;

/**
 * OperationalInsightService - Generates actionable insights for urban operations
 * 
 * Synthesizes incident, analytics, and district data to produce high-level
 * recommendations for operational improvements and infrastructure optimization.
 */
@Service
@Transactional
@RequiredArgsConstructor
@Slf4j
public class OperationalInsightService {

    private final DistrictRepository districtRepository;
    private final IncidentRepository incidentRepository;
    private final AnalyticsEventRepository analyticsEventRepository;
    private final RecommendationRepository recommendationRepository;
    private final HotspotDetectionService hotspotDetectionService;
    private final DistrictRiskScoringService districtRiskScoringService;
    private final TrendAggregationService trendAggregationService;

    public OperationalInsightResponse generateDistrictRecommendations(Long districtId) {
        log.info("Generating recommendations for district: {}", districtId);

        District district = districtRepository.findById(districtId)
            .orElseThrow(() -> new IllegalArgumentException("District not found: " + districtId));

        List<Recommendation> recommendations = analyzeAndGenerateRecommendations(district);
        return buildOperationalInsight(district, recommendations);
    }

    public Page<OperationalInsightResponse> generateAllRecommendations(Pageable pageable) {
        log.info("Generating recommendations for all districts");

        return districtRepository.findAll(pageable)
            .map(district -> buildOperationalInsight(district, analyzeAndGenerateRecommendations(district)));
    }

    @Transactional(readOnly = true)
    public Page<Recommendation> getGeneratedRecommendations(Pageable pageable) {
        log.info("Fetching auto-generated recommendations");
        return recommendationRepository.findByAutoGeneratedTrue(pageable);
    }

    /**
     * Generate comprehensive operational dashboard insights
     */
    public Map<String, Object> generateDashboardInsights() {
        log.info("Generating comprehensive operational dashboard insights");
        
        Map<String, Object> insights = new LinkedHashMap<>();
        
        // System Health
        insights.put("system_health", generateSystemHealth());
        
        // Critical Alerts
        insights.put("critical_alerts", generateCriticalAlerts());
        
        // Operational Recommendations
        insights.put("operational_recommendations", generateOperationalRecommendations());
        
        // Trend Summary
        insights.put("trend_summary", generateTrendSummary());
        
        return insights;
    }

    /**
     * Generate system health overview
     */
    private Map<String, Object> generateSystemHealth() {
        LocalDateTime twentyFourHoursAgo = LocalDateTime.now().minusHours(24);
        
        List<Incident> recentIncidents = incidentRepository.findByCreatedAtAfter(twentyFourHoursAgo);
        long criticalIncidents = recentIncidents.stream()
            .filter(i -> i.getSeverity() == Incident.SeverityLevel.CRITICAL)
            .count();
        long highSeverityIncidents = recentIncidents.stream()
            .filter(i -> i.getSeverity() == Incident.SeverityLevel.HIGH)
            .count();
        
        Map<String, Object> health = new LinkedHashMap<>();
        health.put("total_incidents_24h", recentIncidents.size());
        health.put("critical_incidents", criticalIncidents);
        health.put("high_severity_incidents", highSeverityIncidents);
        health.put("system_status", criticalIncidents > 0 ? "DEGRADED" : "HEALTHY");
        
        return health;
    }

    /**
     * Generate critical alerts requiring immediate attention
     */
    private List<Map<String, Object>> generateCriticalAlerts() {
        List<Map<String, Object>> alerts = new ArrayList<>();
        
        // Alert 1: Critical incidents
        LocalDateTime twentyFourHoursAgo = LocalDateTime.now().minusHours(24);
        List<Incident> criticalIncidents = incidentRepository.findByCreatedAtAfter(twentyFourHoursAgo)
            .stream()
            .filter(i -> i.getSeverity() == Incident.SeverityLevel.CRITICAL)
            .limit(5)
            .collect(Collectors.toList());
        
        if (!criticalIncidents.isEmpty()) {
            Map<String, Object> alert = new LinkedHashMap<>();
            alert.put("type", "CRITICAL_INCIDENTS");
            alert.put("count", criticalIncidents.size());
            alert.put("message", "Critical incidents detected requiring immediate attention");
            alert.put("priority", "IMMEDIATE");
            alerts.add(alert);
        }
        
        // Alert 2: Activity anomalies
        List<Map<String, Object>> anomalies = trendAggregationService.detectActivityAnomalies();
        if (!anomalies.isEmpty() && !anomalies.stream()
            .allMatch(a -> "LOW".equals(a.get("severity")))) {
            Map<String, Object> alert = new LinkedHashMap<>();
            alert.put("type", "ANOMALY_DETECTED");
            alert.put("count", anomalies.size());
            alert.put("message", "Unusual activity patterns detected");
            alert.put("priority", "HIGH");
            alerts.add(alert);
        }
        
        return alerts;
    }

    /**
     * Generate operational recommendations based on current state
     */
    private List<String> generateOperationalRecommendations() {
        List<String> recommendations = new ArrayList<>();
        
        // Recommendation 1: Based on hotspots
        Map<String, Integer> hotspots = hotspotDetectionService.detectIncidentHotspots();
        if (!hotspots.isEmpty()) {
            recommendations.add("Increase monitoring and patrol presence in identified incident hotspots");
        }
        
        // Recommendation 2: Based on sustainability
        List<Map<String, Object>> lowSustainability = districtRiskScoringService.getAllDistrictsRankedByRisk()
            .stream()
            .filter(d -> d.get("risk_level").equals("CRITICAL"))
            .limit(3)
            .collect(Collectors.toList());
        
        if (!lowSustainability.isEmpty()) {
            recommendations.add("Prioritize sustainability initiatives in high-risk districts");
        }
        
        // Recommendation 3: Based on trends
        recommendations.add("Review and adjust resource allocation based on current incident trends");
        
        return recommendations;
    }

    /**
     * Generate trend summary
     */
    private Map<String, Object> generateTrendSummary() {
        Map<String, Object> summary = new LinkedHashMap<>();
        
        Map<String, Long> incidentTrends = trendAggregationService.getIncidentTypeTrends();
        Map<String, Long> categoryDist = trendAggregationService.getAnalyticsCategoryDistribution();
        
        summary.put("top_incident_types", incidentTrends.entrySet().stream()
            .sorted((a, b) -> b.getValue().compareTo(a.getValue()))
            .limit(5)
            .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue, 
                (a, b) -> a, LinkedHashMap::new)));
        
        summary.put("top_categories", categoryDist.entrySet().stream()
            .sorted((a, b) -> b.getValue().compareTo(a.getValue()))
            .limit(5)
            .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue,
                (a, b) -> a, LinkedHashMap::new)));
        
        return summary;
    }

    private List<Recommendation> analyzeAndGenerateRecommendations(District district) {
        List<Recommendation> recommendations = new ArrayList<>();

        recommendations.addAll(analyzeTrafficPatterns(district));
        recommendations.addAll(analyzeInfrastructureRisks(district));
        recommendations.addAll(analyzeSustainabilityTrends(district));
        recommendations.addAll(analyzeIncidentGrowth(district));
        recommendations.addAll(analyzeCriticalIncidents(district));
        recommendations.addAll(analyzeResolutionPerformance(district));

        return recommendations.stream()
            .map(recommendation -> {
                recommendation.setDistrict(district);
                recommendation.setAutoGenerated(true);
                return recommendationRepository.save(recommendation);
            })
            .collect(Collectors.toList());
    }

    private List<Recommendation> analyzeTrafficPatterns(District district) {
        List<Incident> trafficIncidents = incidentRepository.findByDistrict(district).stream()
            .filter(incident -> containsIgnoreCase(incident.getType(), "traffic"))
            .collect(Collectors.toList());

        long unresolved = trafficIncidents.stream().filter(this::isUnresolved).count();
        if (trafficIncidents.size() > 5 && unresolved >= 3) {
            return List.of(Recommendation.builder()
                .type("TRAFFIC_RESPONSE")
                .priority(Recommendation.Priority.CRITICAL)
                .message("High traffic congestion detected. Deploy traffic response teams to "
                    + district.getName() + " immediately. " + unresolved
                    + " unresolved traffic incidents require coordination.")
                .build());
        }
        return List.of();
    }

    private List<Recommendation> analyzeInfrastructureRisks(District district) {
        List<Incident> infrastructureIncidents = incidentRepository.findByDistrict(district).stream()
            .filter(incident -> containsIgnoreCase(incident.getType(), "infrastructure"))
            .collect(Collectors.toList());

        return infrastructureIncidents.stream()
            .collect(Collectors.groupingBy(Incident::getDescription, Collectors.counting()))
            .entrySet()
            .stream()
            .filter(entry -> entry.getValue() >= 3)
            .map(entry -> Recommendation.builder()
                .type("INFRASTRUCTURE_MAINTENANCE")
                .priority(Recommendation.Priority.HIGH)
                .message("Repeated infrastructure issue detected: '" + entry.getKey()
                    + "' has occurred " + entry.getValue()
                    + " times. Prioritize maintenance and preventive measures in "
                    + district.getName() + ".")
                .build())
            .collect(Collectors.toList());
    }

    private List<Recommendation> analyzeSustainabilityTrends(District district) {
        if (district.getSustainabilityScore() < 50) {
            return List.of(Recommendation.builder()
                .type("SUSTAINABILITY_MONITORING")
                .priority(Recommendation.Priority.MEDIUM)
                .message("Sustainability score for " + district.getName()
                    + " is low (" + String.format("%.1f", district.getSustainabilityScore())
                    + "/100). Increase environmental monitoring and implement sustainability improvement initiatives.")
                .build());
        }
        return List.of();
    }

    private List<Recommendation> analyzeIncidentGrowth(District district) {
        LocalDateTime thirtyDaysAgo = LocalDateTime.now().minusDays(30);
        LocalDateTime fifteenDaysAgo = LocalDateTime.now().minusDays(15);
        int earlierIncidents = incidentRepository
            .findByDistrictAndCreatedAtBetween(district, thirtyDaysAgo, fifteenDaysAgo)
            .size();
        int recentIncidents = incidentRepository.findByDistrictAndCreatedAtAfter(district, fifteenDaysAgo).size();

        if (earlierIncidents == 0) {
            return List.of();
        }

        double growthRate = ((recentIncidents - earlierIncidents) / (double) earlierIncidents) * 100;
        if (growthRate > 25) {
            return List.of(Recommendation.builder()
                .type("RESOURCE_ALLOCATION")
                .priority(Recommendation.Priority.HIGH)
                .message("Incident growth of " + String.format("%.1f", growthRate)
                    + "% detected in " + district.getName()
                    + " over past 15 days. Increase operational resources and incident response capacity.")
                .build());
        }
        return List.of();
    }

    private List<Recommendation> analyzeCriticalIncidents(District district) {
        List<Incident> criticalIncidents = incidentRepository.findByDistrictAndSeverity(
            district,
            Incident.SeverityLevel.CRITICAL
        );
        long unresolved = criticalIncidents.stream().filter(this::isUnresolved).count();

        if (criticalIncidents.size() >= 2 && unresolved > 0) {
            return List.of(Recommendation.builder()
                .type("EMERGENCY_COORDINATION")
                .priority(Recommendation.Priority.CRITICAL)
                .message("Multiple critical incidents (" + criticalIncidents.size()
                    + ") in " + district.getName() + " with " + unresolved
                    + " unresolved. Activate emergency response coordination.")
                .build());
        }
        return List.of();
    }

    private List<Recommendation> analyzeResolutionPerformance(District district) {
        List<Incident> allIncidents = incidentRepository.findByDistrict(district);
        if (allIncidents.isEmpty()) {
            return List.of();
        }

        long resolved = allIncidents.stream()
            .filter(i -> i.getStatus() == Incident.IncidentStatus.RESOLVED
                || i.getStatus() == Incident.IncidentStatus.CLOSED)
            .count();
        double resolutionRate = (resolved / (double) allIncidents.size()) * 100;

        if (resolutionRate < 50) {
            return List.of(Recommendation.builder()
                .type("PROCESS_IMPROVEMENT")
                .priority(Recommendation.Priority.MEDIUM)
                .message("Low incident resolution rate (" + String.format("%.1f", resolutionRate)
                    + "%) in " + district.getName()
                    + ". Review and improve incident handling processes.")
                .build());
        }
        return List.of();
    }

    private OperationalInsightResponse buildOperationalInsight(District district, List<Recommendation> recommendations) {
        return OperationalInsightResponse.builder()
            .districtId(district.getId())
            .districtName(district.getName())
            .generatedRecommendationCount(recommendations.size())
            .criticalRecommendations((int) recommendations.stream()
                .filter(r -> r.getPriority() == Recommendation.Priority.CRITICAL)
                .count())
            .highPriorityRecommendations((int) recommendations.stream()
                .filter(r -> r.getPriority() == Recommendation.Priority.HIGH)
                .count())
            .recommendations(recommendations)
            .generatedAt(LocalDateTime.now())
            .build();
    }

    private boolean isUnresolved(Incident incident) {
        return incident.getStatus() == Incident.IncidentStatus.REPORTED
            || incident.getStatus() == Incident.IncidentStatus.IN_PROGRESS;
    }

    private boolean containsIgnoreCase(String value, String needle) {
        return value != null && value.toLowerCase(Locale.ROOT).contains(needle.toLowerCase(Locale.ROOT));
    }
}
