package com.urban.intelligence.platform.analytics;

import com.urban.intelligence.platform.domain.entity.District;
import com.urban.intelligence.platform.domain.entity.Incident;
import com.urban.intelligence.platform.domain.entity.Recommendation;
import com.urban.intelligence.platform.domain.repository.AnalyticsEventRepository;
import com.urban.intelligence.platform.domain.repository.DistrictRepository;
import com.urban.intelligence.platform.domain.repository.IncidentRepository;
import com.urban.intelligence.platform.domain.repository.RecommendationRepository;
import com.urban.intelligence.platform.dto.analytics.OperationalInsightResponse;
import io.micrometer.core.annotation.Timed;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.*;
import java.util.stream.Collectors;

/**
 * OperationalInsightService - Generates actionable insights for urban operations.
 *
 * Synthesizes incident, analytics, and district data to produce high-level
 * recommendations for operational improvements.
 *
 * Performance: uses a single incident load per district within analyzeAndGenerateRecommendations
 * to avoid N+1 queries across the 6 analysis methods.
 */
@Service
@Transactional
@RequiredArgsConstructor
@Slf4j
public class OperationalInsightService {

    private final DistrictRepository districtRepository;
    private final IncidentRepository incidentRepository;
    private final AnalyticsEventRepository analyticsEventRepository;
    private final RecommendationRepository recommendationRepository;
    private final HotspotDetectionService hotspotDetectionService;
    private final DistrictRiskScoringService districtRiskScoringService;
    private final TrendAggregationService trendAggregationService;

    @Timed(value = "analytics.execution.time", extraTags = {"service", "insight"})
    public OperationalInsightResponse generateDistrictRecommendations(Long districtId) {
        log.info("Generating recommendations for district: {}", districtId);

        District district = districtRepository.findById(districtId)
            .orElseThrow(() -> new IllegalArgumentException("District not found: " + districtId));

        // Single query: load all incidents for this district at once
        List<Incident> allIncidents = incidentRepository.findByDistrictWithFetch(district);
        List<Recommendation> recommendations = analyzeAndGenerateRecommendations(district, allIncidents);
        return buildOperationalInsight(district, recommendations);
    }

    @Timed(value = "analytics.execution.time", extraTags = {"service", "insight"})
    public Page<OperationalInsightResponse> generateAllRecommendations(Pageable pageable) {
        log.info("Generating recommendations for all districts");

        return districtRepository.findAll(pageable)
            .map(district -> {
                List<Incident> allIncidents = incidentRepository.findByDistrictWithFetch(district);
                return buildOperationalInsight(district, analyzeAndGenerateRecommendations(district, allIncidents));
            });
    }

    @Transactional(readOnly = true)
    public Page<Recommendation> getGeneratedRecommendations(Pageable pageable) {
        log.info("Fetching auto-generated recommendations");
        return recommendationRepository.findByAutoGeneratedTrue(pageable);
    }

    /**
     * Generate comprehensive operational dashboard insights.
     * Avoids re-querying incidents by sharing the same 24h batch.
     */
    public Map<String, Object> generateDashboardInsights() {
        log.info("Generating comprehensive operational dashboard insights");

        // Single batch load: all incidents from last 24h, shared across health + alerts
        LocalDateTime twentyFourHoursAgo = LocalDateTime.now().minusHours(24);
        List<Incident> recentIncidents = incidentRepository.findByCreatedAtAfter(twentyFourHoursAgo);

        Map<String, Object> insights = new LinkedHashMap<>();
        insights.put("system_health", generateSystemHealth(recentIncidents));
        insights.put("critical_alerts", generateCriticalAlerts(recentIncidents));
        insights.put("operational_recommendations", generateOperationalRecommendations());
        insights.put("trend_summary", generateTrendSummary());

        return insights;
    }

    /**
     * Generate system health overview from pre-loaded incidents (no extra query).
     */
    private Map<String, Object> generateSystemHealth(List<Incident> recentIncidents) {
        long criticalIncidents = recentIncidents.stream()
            .filter(i -> i.getSeverity() == Incident.SeverityLevel.CRITICAL)
            .count();
        long highSeverityIncidents = recentIncidents.stream()
            .filter(i -> i.getSeverity() == Incident.SeverityLevel.HIGH)
            .count();

        Map<String, Object> health = new LinkedHashMap<>();
        health.put("total_incidents_24h", recentIncidents.size());
        health.put("critical_incidents", criticalIncidents);
        health.put("high_severity_incidents", highSeverityIncidents);
        health.put("system_status", criticalIncidents > 0 ? "DEGRADED" : "HEALTHY");

        return health;
    }

    /**
     * Generate critical alerts from pre-loaded incidents (no extra query).
     */
    private List<Map<String, Object>> generateCriticalAlerts(List<Incident> recentIncidents) {
        List<Map<String, Object>> alerts = new ArrayList<>();

        // Alert 1: Critical incidents (use already-loaded list, avoid re-query)
        List<Incident> criticalIncidents = recentIncidents.stream()
            .filter(i -> i.getSeverity() == Incident.SeverityLevel.CRITICAL)
            .limit(5)
            .collect(Collectors.toList());

        if (!criticalIncidents.isEmpty()) {
            Map<String, Object> alert = new LinkedHashMap<>();
            alert.put("type", "CRITICAL_INCIDENTS");
            alert.put("count", criticalIncidents.size());
            alert.put("message", "Critical incidents detected requiring immediate attention");
            alert.put("priority", "IMMEDIATE");
            alerts.add(alert);
        }

        // Alert 2: Activity anomalies
        List<Map<String, Object>> anomalies = trendAggregationService.detectActivityAnomalies();
        if (!anomalies.isEmpty() && !anomalies.stream()
            .allMatch(a -> "LOW".equals(a.get("severity")))) {
            Map<String, Object> alert = new LinkedHashMap<>();
            alert.put("type", "ANOMALY_DETECTED");
            alert.put("count", anomalies.size());
            alert.put("message", "Unusual activity patterns detected");
            alert.put("priority", "HIGH");
            alerts.add(alert);
        }

        return alerts;
    }

    private List<String> generateOperationalRecommendations() {
        List<String> recommendations = new ArrayList<>();

        Map<String, Integer> hotspots = hotspotDetectionService.detectIncidentHotspots();
        if (!hotspots.isEmpty()) {
            recommendations.add("Increase monitoring and patrol presence in identified incident hotspots");
        }

        List<Map<String, Object>> lowSustainability = districtRiskScoringService.getAllDistrictsRankedByRisk()
            .stream()
            .filter(d -> d.get("risk_level").equals("CRITICAL"))
            .limit(3)
            .collect(Collectors.toList());

        if (!lowSustainability.isEmpty()) {
            recommendations.add("Prioritize sustainability initiatives in high-risk districts");
        }

        recommendations.add("Review and adjust resource allocation based on current incident trends");

        return recommendations;
    }

    private Map<String, Object> generateTrendSummary() {
        Map<String, Object> summary = new LinkedHashMap<>();

        Map<String, Long> incidentTrends = trendAggregationService.getIncidentTypeTrends();
        Map<String, Long> categoryDist = trendAggregationService.getAnalyticsCategoryDistribution();

        summary.put("top_incident_types", incidentTrends.entrySet().stream()
            .sorted((a, b) -> b.getValue().compareTo(a.getValue()))
            .limit(5)
            .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue,
                (a, b) -> a, LinkedHashMap::new)));

        summary.put("top_categories", categoryDist.entrySet().stream()
            .sorted((a, b) -> b.getValue().compareTo(a.getValue()))
            .limit(5)
            .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue,
                (a, b) -> a, LinkedHashMap::new)));

        return summary;
    }

    /**
     * Analyze all recommendation types using a single pre-loaded incident list per district.
     * This avoids N+1: 6 separate incidentRepository queries per district → 1 shared query.
     */
    private List<Recommendation> analyzeAndGenerateRecommendations(District district, List<Incident> allIncidents) {
        List<Recommendation> recommendations = new ArrayList<>();

        recommendations.addAll(analyzeTrafficPatterns(allIncidents));
        recommendations.addAll(analyzeInfrastructureRisks(allIncidents));
        recommendations.addAll(analyzeSustainabilityTrends(district));
        recommendations.addAll(analyzeIncidentGrowth(allIncidents, district));
        recommendations.addAll(analyzeCriticalIncidents(allIncidents));
        recommendations.addAll(analyzeResolutionPerformance(allIncidents));

        return recommendations.stream()
            .map(recommendation -> {
                recommendation.setDistrict(district);
                recommendation.setAutoGenerated(true);
                return recommendationRepository.save(recommendation);
            })
            .collect(Collectors.toList());
    }

    private List<Recommendation> analyzeTrafficPatterns(List<Incident> allIncidents) {
        List<Incident> trafficIncidents = allIncidents.stream()
            .filter(incident -> containsIgnoreCase(incident.getType(), "traffic"))
            .collect(Collectors.toList());

        long unresolved = trafficIncidents.stream().filter(this::isUnresolved).count();
        if (trafficIncidents.size() > 5 && unresolved >= 3) {
            return List.of(Recommendation.builder()
                .type("TRAFFIC_RESPONSE")
                .priority(Recommendation.Priority.CRITICAL)
                .message("High traffic congestion detected. Deploy traffic response teams immediately. "
                    + unresolved + " unresolved traffic incidents require coordination.")
                .build());
        }
        return List.of();
    }

    private List<Recommendation> analyzeInfrastructureRisks(List<Incident> allIncidents) {
        List<Incident> infrastructureIncidents = allIncidents.stream()
            .filter(incident -> containsIgnoreCase(incident.getType(), "infrastructure"))
            .collect(Collectors.toList());

        return infrastructureIncidents.stream()
            .collect(Collectors.groupingBy(Incident::getDescription, Collectors.counting()))
            .entrySet()
            .stream()
            .filter(entry -> entry.getValue() >= 3)
            .map(entry -> Recommendation.builder()
                .type("INFRASTRUCTURE_MAINTENANCE")
                .priority(Recommendation.Priority.HIGH)
                .message("Repeated infrastructure issue detected: '" + entry.getKey()
                    + "' has occurred " + entry.getValue()
                    + " times. Prioritize maintenance and preventive measures.")
                .build())
            .collect(Collectors.toList());
    }

    private List<Recommendation> analyzeSustainabilityTrends(District district) {
        if (district.getSustainabilityScore() < 50) {
            return List.of(Recommendation.builder()
                .type("SUSTAINABILITY_MONITORING")
                .priority(Recommendation.Priority.MEDIUM)
                .message("Sustainability score for " + district.getName()
                    + " is low (" + String.format("%.1f", district.getSustainabilityScore())
                    + "/100). Increase environmental monitoring and implement sustainability improvement initiatives.")
                .build());
        }
        return List.of();
    }

    private List<Recommendation> analyzeIncidentGrowth(List<Incident> allIncidents, District district) {
        LocalDateTime thirtyDaysAgo = LocalDateTime.now().minusDays(30);
        LocalDateTime fifteenDaysAgo = LocalDateTime.now().minusDays(15);

        long earlierIncidents = allIncidents.stream()
            .filter(i -> !i.getCreatedAt().isBefore(thirtyDaysAgo) && i.getCreatedAt().isBefore(fifteenDaysAgo))
            .count();
        long recentIncidents = allIncidents.stream()
            .filter(i -> !i.getCreatedAt().isBefore(fifteenDaysAgo))
            .count();

        if (earlierIncidents == 0) {
            return List.of();
        }

        double growthRate = ((recentIncidents - earlierIncidents) / (double) earlierIncidents) * 100;
        if (growthRate > 25) {
            return List.of(Recommendation.builder()
                .type("RESOURCE_ALLOCATION")
                .priority(Recommendation.Priority.HIGH)
                .message("Incident growth of " + String.format("%.1f", growthRate)
                    + "% detected in " + district.getName()
                    + " over past 15 days. Increase operational resources and incident response capacity.")
                .build());
        }
        return List.of();
    }

    private List<Recommendation> analyzeCriticalIncidents(List<Incident> allIncidents) {
        List<Incident> criticalIncidents = allIncidents.stream()
            .filter(i -> i.getSeverity() == Incident.SeverityLevel.CRITICAL)
            .collect(Collectors.toList());
        long unresolved = criticalIncidents.stream().filter(this::isUnresolved).count();

        if (criticalIncidents.size() >= 2 && unresolved > 0) {
            return List.of(Recommendation.builder()
                .type("EMERGENCY_COORDINATION")
                .priority(Recommendation.Priority.CRITICAL)
                .message("Multiple critical incidents (" + criticalIncidents.size()
                    + ") with " + unresolved
                    + " unresolved. Activate emergency response coordination.")
                .build());
        }
        return List.of();
    }

    private List<Recommendation> analyzeResolutionPerformance(List<Incident> allIncidents) {
        if (allIncidents.isEmpty()) {
            return List.of();
        }

        long resolved = allIncidents.stream()
            .filter(i -> i.getStatus() == Incident.IncidentStatus.RESOLVED
                || i.getStatus() == Incident.IncidentStatus.CLOSED)
            .count();
        double resolutionRate = (resolved / (double) allIncidents.size()) * 100;

        if (resolutionRate < 50) {
            return List.of(Recommendation.builder()
                .type("PROCESS_IMPROVEMENT")
                .priority(Recommendation.Priority.MEDIUM)
                .message("Low incident resolution rate (" + String.format("%.1f", resolutionRate)
                    + "%). Review and improve incident handling processes.")
                .build());
        }
        return List.of();
    }

    private OperationalInsightResponse buildOperationalInsight(District district, List<Recommendation> recommendations) {
        return OperationalInsightResponse.builder()
            .districtId(district.getId())
            .districtName(district.getName())
            .generatedRecommendationCount(recommendations.size())
            .criticalRecommendations((int) recommendations.stream()
                .filter(r -> r.getPriority() == Recommendation.Priority.CRITICAL)
                .count())
            .highPriorityRecommendations((int) recommendations.stream()
                .filter(r -> r.getPriority() == Recommendation.Priority.HIGH)
                .count())
            .recommendations(recommendations)
            .generatedAt(LocalDateTime.now())
            .build();
    }

    private boolean isUnresolved(Incident incident) {
        return incident.getStatus() == Incident.IncidentStatus.REPORTED
            || incident.getStatus() == Incident.IncidentStatus.IN_PROGRESS;
    }

    private boolean containsIgnoreCase(String value, String needle) {
        return value != null && value.toLowerCase(Locale.ROOT).contains(needle.toLowerCase(Locale.ROOT));
    }
}