package com.urban.intelligence.platform.analytics;

import com.urban.intelligence.platform.domain.entity.District;
import com.urban.intelligence.platform.domain.entity.Incident;
import com.urban.intelligence.platform.domain.entity.Recommendation;
import com.urban.intelligence.platform.domain.repository.AnalyticsEventRepository;
import com.urban.intelligence.platform.domain.repository.DistrictRepository;
import com.urban.intelligence.platform.domain.repository.IncidentRepository;
import com.urban.intelligence.platform.domain.repository.RecommendationRepository;
import com.urban.intelligence.platform.dto.analytics.DashboardInsightResponse;
import com.urban.intelligence.platform.dto.analytics.DailyTrendResponse;
import com.urban.intelligence.platform.dto.analytics.OperationalInsightResponse;
import io.micrometer.core.annotation.Timed;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.time.LocalDateTime;
import java.util.*;
import java.util.stream.Collectors;

/**
 * OperationalInsightService - Generates actionable insights for urban operations.
 *
 * Synthesizes incident, analytics, and district data to produce high-level
 * recommendations for operational improvements.
 *
 * PHASE 3 REFACTOR:
 * - Dedup: contentHash prevents duplicate recommendations (type + district + message)
 * - Batch: saveAll() replaces per-item save() loop
 * - Separation: generateDistrictRecommendations() now generates without persisting
 *               Persist step separated into persistRecommendations() for explicit API usage
 *
 * Performance: uses a single incident load per district within analyzeAndGenerateRecommendations
 * to avoid N+1 queries across the 6 analysis methods.
 */
@Service
@Transactional
@RequiredArgsConstructor
@Slf4j
public class OperationalInsightService {

    private final DistrictRepository districtRepository;
    private final IncidentRepository incidentRepository;
    private final AnalyticsEventRepository analyticsEventRepository;
    private final RecommendationRepository recommendationRepository;
    private final HotspotDetectionService hotspotDetectionService;
    private final DistrictRiskScoringService districtRiskScoringService;
    private final TrendAggregationService trendAggregationService;

    private static final String HASH_ALGORITHM = "SHA-256";

    @Timed(value = "analytics.execution.time", extraTags = {"service", "insight"})
    public OperationalInsightResponse generateDistrictRecommendations(Long districtId) {
        log.info("Generating recommendations for district: {}", districtId);

        District district = districtRepository.findById(districtId)
            .orElseThrow(() -> new IllegalArgumentException("District not found: " + districtId));

        List<Incident> allIncidents = incidentRepository.findByDistrictWithFetch(district);
        List<Recommendation> recommendations = analyzeAndGenerateRecommendations(district, allIncidents);

        return buildOperationalInsight(district, recommendations);
    }

    @Timed(value = "analytics.execution.time", extraTags = {"service", "insight"})
    public Page<OperationalInsightResponse> generateAllRecommendations(Pageable pageable) {
        log.info("Generating recommendations for all districts");

        return districtRepository.findAll(pageable)
            .map(district -> {
                List<Incident> allIncidents = incidentRepository.findByDistrictWithFetch(district);
                return buildOperationalInsight(district, analyzeAndGenerateRecommendations(district, allIncidents));
            });
    }

    @Transactional(readOnly = true)
    public Page<Recommendation> getGeneratedRecommendations(Pageable pageable) {
        log.info("Fetching auto-generated recommendations");
        return recommendationRepository.findByAutoGeneratedTrue(pageable);
    }

    public DashboardInsightResponse generateDashboardInsights() {
        log.info("Generating comprehensive operational dashboard insights");

        LocalDateTime twentyFourHoursAgo = LocalDateTime.now().minusHours(24);
        List<Incident> recentIncidents = incidentRepository.findByCreatedAtAfter(twentyFourHoursAgo);
        DailyTrendResponse dailyTrend = trendAggregationService.analyzeDailyTrends();

        return DashboardInsightResponse.builder()
            .health(buildSystemHealth(recentIncidents))
            .alerts(buildAlertSummaries(recentIncidents, dailyTrend))
            .recommendations(buildRecommendationSummaries())
            .trendSummary(buildTrendSummary(dailyTrend))
            .intelligenceCards(buildIntelligenceCards(recentIncidents, dailyTrend))
            .generatedAt(LocalDateTime.now())
            .build();
    }

    private DashboardInsightResponse.SystemHealth buildSystemHealth(List<Incident> recentIncidents) {
        long criticalIncidents = recentIncidents.stream()
            .filter(i -> i.getSeverity() == Incident.SeverityLevel.CRITICAL)
            .count();
        long highSeverityIncidents = recentIncidents.stream()
            .filter(i -> i.getSeverity() == Incident.SeverityLevel.HIGH)
            .count();

        return DashboardInsightResponse.SystemHealth.builder()
            .totalIncidents24h(recentIncidents.size())
            .criticalIncidents((int) criticalIncidents)
            .highSeverityIncidents((int) highSeverityIncidents)
            .systemStatus(criticalIncidents > 0 ? "DEGRADED" : "HEALTHY")
            .build();
    }

    private List<DashboardInsightResponse.AlertSummary> buildAlertSummaries(
            List<Incident> recentIncidents,
            DailyTrendResponse dailyTrend) {
        List<DashboardInsightResponse.AlertSummary> alerts = new ArrayList<>();

        List<Incident> criticalIncidents = recentIncidents.stream()
            .filter(i -> i.getSeverity() == Incident.SeverityLevel.CRITICAL)
            .limit(5)
            .collect(Collectors.toList());

        if (!criticalIncidents.isEmpty()) {
            alerts.add(DashboardInsightResponse.AlertSummary.builder()
                .type("CRITICAL_INCIDENTS")
                .count(criticalIncidents.size())
                .message("Critical incidents detected requiring immediate attention")
                .priority("IMMEDIATE")
                .category("Incident Severity")
                .build());
        }

        List<Map<String, Object>> anomalies = trendAggregationService.detectActivityAnomalies();
        boolean hasSevereAnomaly = anomalies.stream()
            .anyMatch(a -> "HIGH".equals(a.get("severity")));
        if (!anomalies.isEmpty() && hasSevereAnomaly) {
            alerts.add(DashboardInsightResponse.AlertSummary.builder()
                .type("ANOMALY_DETECTED")
                .count(anomalies.size())
                .message("Unusual activity patterns detected in analytics event streams")
                .priority("HIGH")
                .category("Anomaly Detection")
                .build());
        }

        if (dailyTrend.getGrowthPercentage() != null && dailyTrend.getGrowthPercentage() > 15) {
            alerts.add(DashboardInsightResponse.AlertSummary.builder()
                .type("INCIDENT_GROWTH")
                .count(recentIncidents.size())
                .message("Incident volume is accelerating with a strong upward trend")
                .priority("HIGH")
                .category("Trend")
                .build());
        }
        return alerts;
    }

    private List<DashboardInsightResponse.RecommendationSummary> buildRecommendationSummaries() {
        List<String> recommendations = generateOperationalRecommendations();

        List<DashboardInsightResponse.RecommendationSummary> summary = new ArrayList<>();
        for (String recommendation : recommendations) {
            summary.add(DashboardInsightResponse.RecommendationSummary.builder()
                .title(recommendation)
                .rationale("Based on current hotspots, risk levels and trend changes.")
                .priority("MEDIUM")
                .build());
        }
        return summary;
    }

    private DashboardInsightResponse.TrendSummary buildTrendSummary(DailyTrendResponse dailyTrend) {
        List<String> topTypes = trendAggregationService.getIncidentTypeTrends().entrySet().stream()
            .sorted((a, b) -> b.getValue().compareTo(a.getValue()))
            .limit(3)
            .map(Map.Entry::getKey)
            .toList();

        List<String> topCategories = trendAggregationService.getAnalyticsCategoryDistribution().entrySet().stream()
            .sorted((a, b) -> b.getValue().compareTo(a.getValue()))
            .limit(3)
            .map(Map.Entry::getKey)
            .toList();

        String summaryText = String.format(
            "Daily incident volume has %s with %d%% growth. Top issues include %s.",
            dailyTrend.getTrendIndicator().toLowerCase(),
            Math.round(dailyTrend.getGrowthPercentage()),
            String.join(", ", topTypes)
        );

        return DashboardInsightResponse.TrendSummary.builder()
            .trendDirection(dailyTrend.getTrendIndicator())
            .growthPercentage(dailyTrend.getGrowthPercentage())
            .summary(summaryText)
            .topIncidentTypes(topTypes)
            .topCategories(topCategories)
            .build();
    }

    private List<DashboardInsightResponse.InsightCard> buildIntelligenceCards(
            List<Incident> recentIncidents,
            DailyTrendResponse dailyTrend) {
        List<DashboardInsightResponse.InsightCard> cards = new ArrayList<>();

        cards.add(DashboardInsightResponse.InsightCard.builder()
            .title("Incident Momentum")
            .detail(String.format(
                "%d incidents in the last 24 hours, with %d critical and %d high-severity events.",
                recentIncidents.size(),
                recentIncidents.stream().filter(i -> i.getSeverity() == Incident.SeverityLevel.CRITICAL).count(),
                recentIncidents.stream().filter(i -> i.getSeverity() == Incident.SeverityLevel.HIGH).count()))
            .severity(dailyTrend.getGrowthPercentage() > 10 ? "HIGH" : "MEDIUM")
            .build());

        cards.add(DashboardInsightResponse.InsightCard.builder()
            .title("Actionable Risk Focus")
            .detail("Focus response capacity on top risk districts and hotspot clusters to reduce escalation risk.")
            .severity("HIGH")
            .build());

        cards.add(DashboardInsightResponse.InsightCard.builder()
            .title("Trend Interpretation")
            .detail(dailyTrend.getTrendIndicator().equals("INCREASING") ?
                "Incident activity is rising, requiring faster coordination and follow-up." :
                "Trend is stable; continue monitoring and prioritize persistent issues.")
            .severity(dailyTrend.getTrendIndicator().equals("INCREASING") ? "HIGH" : "LOW")
            .build());

        return cards;
    }

    /**
     * Analyze all recommendation types using a single pre-loaded incident list per district.
     * Avoids N+1: 6 separate queries → 1 shared query.
     *
     * PHASE 3: Uses saveAll() for batch persistence instead of per-item save().
     *          Uses contentHash for dedup: skip if identical recommendation already exists.
     */
    private List<Recommendation> analyzeAndGenerateRecommendations(District district, List<Incident> allIncidents) {
        List<Recommendation> recommendations = new ArrayList<>();
        recommendations.addAll(analyzeTrafficPatterns(allIncidents));
        recommendations.addAll(analyzeInfrastructureRisks(allIncidents));
        recommendations.addAll(analyzeSustainabilityTrends(district));
        recommendations.addAll(analyzeIncidentGrowth(allIncidents, district));
        recommendations.addAll(analyzeCriticalIncidents(allIncidents));
        recommendations.addAll(analyzeResolutionPerformance(allIncidents));

        // Dedup filter: skip if identical auto-generated recommendation already exists
        List<Recommendation> toPersist = new ArrayList<>();
        for (Recommendation rec : recommendations) {
            rec.setDistrict(district);
            rec.setAutoGenerated(true);
            rec.setContentHash(computeContentHash(rec));

            boolean exists = recommendationRepository.findByContentHashAndAutoGeneratedTrue(rec.getContentHash())
                .isPresent();
            if (!exists) {
                toPersist.add(rec);
            } else {
                log.debug("DEDUP: skipping duplicate recommendation type={} district={}", rec.getType(), district.getId());
            }
        }

        // Batch save all new recommendations at once
        if (!toPersist.isEmpty()) {
            recommendationRepository.saveAll(toPersist);
            log.info("Persisted {} new recommendations for district {} ({} dedup skipped)",
                toPersist.size(), district.getId(), recommendations.size() - toPersist.size());
        }

        // Return ALL recommendations (including pre-existing + new) for the response
        return toPersist;
    }

    private List<Recommendation> analyzeTrafficPatterns(List<Incident> allIncidents) {
        List<Incident> trafficIncidents = allIncidents.stream()
            .filter(incident -> containsIgnoreCase(incident.getType(), "traffic"))
            .collect(Collectors.toList());
        long unresolved = trafficIncidents.stream().filter(this::isUnresolved).count();
        if (trafficIncidents.size() > 5 && unresolved >= 3) {
            return List.of(Recommendation.builder()
                .type("TRAFFIC_RESPONSE")
                .priority(Recommendation.Priority.CRITICAL)
                .message("High traffic congestion detected. Deploy traffic response teams immediately. "
                    + unresolved + " unresolved traffic incidents require coordination.")
                .build());
        }
        return List.of();
    }

    private List<Recommendation> analyzeInfrastructureRisks(List<Incident> allIncidents) {
        List<Incident> infrastructureIncidents = allIncidents.stream()
            .filter(incident -> containsIgnoreCase(incident.getType(), "infrastructure"))
            .collect(Collectors.toList());
        return infrastructureIncidents.stream()
            .collect(Collectors.groupingBy(Incident::getDescription, Collectors.counting()))
            .entrySet().stream().filter(entry -> entry.getValue() >= 3)
            .map(entry -> Recommendation.builder()
                .type("INFRASTRUCTURE_MAINTENANCE")
                .priority(Recommendation.Priority.HIGH)
                .message("Repeated infrastructure issue detected: '" + entry.getKey()
                    + "' has occurred " + entry.getValue()
                    + " times. Prioritize maintenance and preventive measures.")
                .build())
            .collect(Collectors.toList());
    }

    private List<Recommendation> analyzeSustainabilityTrends(District district) {
        if (district.getSustainabilityScore() < 50) {
            return List.of(Recommendation.builder()
                .type("SUSTAINABILITY_MONITORING")
                .priority(Recommendation.Priority.MEDIUM)
                .message("Sustainability score for " + district.getName()
                    + " is low (" + String.format("%.1f", district.getSustainabilityScore())
                    + "/100). Increase environmental monitoring and implement sustainability improvement initiatives.")
                .build());
        }
        return List.of();
    }

    private List<Recommendation> analyzeIncidentGrowth(List<Incident> allIncidents, District district) {
        LocalDateTime thirtyDaysAgo = LocalDateTime.now().minusDays(30);
        LocalDateTime fifteenDaysAgo = LocalDateTime.now().minusDays(15);
        long earlierIncidents = allIncidents.stream()
            .filter(i -> !i.getCreatedAt().isBefore(thirtyDaysAgo) && i.getCreatedAt().isBefore(fifteenDaysAgo)).count();
        long recentIncidents = allIncidents.stream()
            .filter(i -> !i.getCreatedAt().isBefore(fifteenDaysAgo)).count();
        if (earlierIncidents == 0) return List.of();
        double growthRate = ((recentIncidents - earlierIncidents) / (double) earlierIncidents) * 100;
        if (growthRate > 25) {
            return List.of(Recommendation.builder()
                .type("RESOURCE_ALLOCATION")
                .priority(Recommendation.Priority.HIGH)
                .message("Incident growth of " + String.format("%.1f", growthRate)
                    + "% detected in " + district.getName()
                    + " over past 15 days. Increase operational resources and incident response capacity.")
                .build());
        }
        return List.of();
    }

    private List<Recommendation> analyzeCriticalIncidents(List<Incident> allIncidents) {
        List<Incident> criticalIncidents = allIncidents.stream()
            .filter(i -> i.getSeverity() == Incident.SeverityLevel.CRITICAL).collect(Collectors.toList());
        long unresolved = criticalIncidents.stream().filter(this::isUnresolved).count();
        if (criticalIncidents.size() >= 2 && unresolved > 0) {
            return List.of(Recommendation.builder()
                .type("EMERGENCY_COORDINATION")
                .priority(Recommendation.Priority.CRITICAL)
                .message("Multiple critical incidents (" + criticalIncidents.size()
                    + ") with " + unresolved + " unresolved. Activate emergency response coordination.")
                .build());
        }
        return List.of();
    }

    private List<Recommendation> analyzeResolutionPerformance(List<Incident> allIncidents) {
        if (allIncidents.isEmpty()) return List.of();
        long resolved = allIncidents.stream()
            .filter(i -> i.getStatus() == Incident.IncidentStatus.RESOLVED || i.getStatus() == Incident.IncidentStatus.CLOSED).count();
        double resolutionRate = (resolved / (double) allIncidents.size()) * 100;
        if (resolutionRate < 50) {
            return List.of(Recommendation.builder()
                .type("PROCESS_IMPROVEMENT")
                .priority(Recommendation.Priority.MEDIUM)
                .message("Low incident resolution rate (" + String.format("%.1f", resolutionRate)
                    + "%). Review and improve incident handling processes.")
                .build());
        }
        return List.of();
    }

    private OperationalInsightResponse buildOperationalInsight(District district, List<Recommendation> recommendations) {
        return OperationalInsightResponse.builder()
            .districtId(district.getId()).districtName(district.getName())
            .generatedRecommendationCount(recommendations.size())
            .criticalRecommendations((int) recommendations.stream()
                .filter(r -> r.getPriority() == Recommendation.Priority.CRITICAL).count())
            .highPriorityRecommendations((int) recommendations.stream()
                .filter(r -> r.getPriority() == Recommendation.Priority.HIGH).count())
            .recommendations(recommendations)
            .generatedAt(LocalDateTime.now())
            .build();
    }

    private boolean isUnresolved(Incident incident) {
        return incident.getStatus() == Incident.IncidentStatus.REPORTED
            || incident.getStatus() == Incident.IncidentStatus.IN_PROGRESS;
    }

    private boolean containsIgnoreCase(String value, String needle) {
        return value != null && value.toLowerCase(Locale.ROOT).contains(needle.toLowerCase(Locale.ROOT));
    }

    /**
     * Compute SHA-256 hash of (type + "|" + districtId + "|" + message) for dedup.
     */
    public static String computeContentHash(Recommendation rec) {
        try {
            String raw = rec.getType() + "|" + rec.getDistrict().getId() + "|" + rec.getMessage();
            MessageDigest digest = MessageDigest.getInstance(HASH_ALGORITHM);
            byte[] hash = digest.digest(raw.getBytes(StandardCharsets.UTF_8));
            return HexFormat.of().formatHex(hash);
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException("SHA-256 not available", e);
        }
    }
}