package com.urban.intelligence.platform.domain.repository;

import com.urban.intelligence.platform.domain.entity.Recommendation;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;
import java.util.List;

/**
 * RecommendationRepository - Data access layer for Recommendation entities
 */
@Repository
public interface RecommendationRepository extends JpaRepository<Recommendation, Long> {

    Page<Recommendation> findByDistrict_Id(Long districtId, Pageable pageable);

    Page<Recommendation> findByPriority(Recommendation.Priority priority, Pageable pageable);

    Page<Recommendation> findByAutoGeneratedTrue(Pageable pageable);

    List<Recommendation> findByCreatedAtAfter(LocalDateTime timestamp);

    @Query("SELECT r FROM Recommendation r WHERE r.district.id = :districtId " +
           "AND r.priority IN ('HIGH', 'CRITICAL') " +
           "ORDER BY r.priority DESC, r.createdAt DESC")
    List<Recommendation> findUrgentRecommendationsByDistrict(@Param("districtId") Long districtId);

    @Query("SELECT r.priority, COUNT(r) FROM Recommendation r " +
           "WHERE r.createdAt >= :startDate GROUP BY r.priority")
    List<Object[]> getRecommendationPriorityDistribution(@Param("startDate") LocalDateTime startDate);

    Long countByPriority(Recommendation.Priority priority);

    Long countByDistrict_Id(Long districtId);
}
