package com.urban.intelligence.platform.config;

import com.urban.intelligence.platform.auth.repository.RefreshTokenSessionRepository;
import com.urban.intelligence.platform.domain.repository.AnalyticsEventRepository;
import com.urban.intelligence.platform.domain.repository.RecommendationRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.time.Instant;
import java.time.LocalDateTime;

/**
 * Scheduled cleanup jobs for data retention management.
 *
 * PHASE 6: Production operational improvements.
 *
 * Tasks:
 * 1. Expired refresh token cleanup — daily
 * 2. Old auto-generated recommendation cleanup — weekly
 * 3. Analytics event archival preparation — daily (identifies candidates only)
 */
@Component
@RequiredArgsConstructor
@Slf4j
public class DataCleanupScheduler {

    private final RefreshTokenSessionRepository refreshTokenSessionRepository;
    private final RecommendationRepository recommendationRepository;
    private final AnalyticsEventRepository analyticsEventRepository;

    /**
     * Remove expired refresh tokens daily at 3:00 AM.
     * Tokens are hashed so no JWT secrets are leaked even in logs.
     */
    @Scheduled(cron = "0 0 3 * * ?")
    @Transactional
    public void purgeExpiredRefreshTokens() {
        log.info("SCHEDULER: purging expired refresh tokens");
        int deleted = refreshTokenSessionRepository.deleteByExpiresAtBefore(Instant.now());
        if (deleted > 0) {
            log.info("SCHEDULER: removed {} expired refresh token sessions", deleted);
        }
    }

    /**
     * Remove auto-generated recommendations older than 90 days weekly on Sunday at 4:00 AM.
     */
    @Scheduled(cron = "0 0 4 * * SUN")
    @Transactional
    public void purgeOldRecommendations() {
        log.info("SCHEDULER: purging auto-generated recommendations older than 90 days");
        LocalDateTime cutoff = LocalDateTime.now().minusDays(90);
        recommendationRepository.deleteOldAutoGenerated(cutoff);
        log.info("SCHEDULER: old recommendation cleanup completed (cutoff={})", cutoff);
    }

    /**
     * Log analytics event retention count daily at 5:00 AM.
     * Future improvement: archive to cold storage before deletion.
     */
    @Scheduled(cron = "0 0 5 * * ?")
    @Transactional(readOnly = true)
    public void reportAnalyticsRetention() {
        LocalDateTime thirtyDaysAgo = LocalDateTime.now().minusDays(30);
        long oldEvents = analyticsEventRepository.countByTimestampBefore(thirtyDaysAgo);
        if (oldEvents > 1000) {
            log.warn("RETENTION: {} analytics events older than 30 days exist. Consider archival.", oldEvents);
        } else {
            log.info("RETENTION: {} analytics events older than 30 days", oldEvents);
        }
    }
}